//#include "isr.h"
//
//#define ISR_DEFINITION_NO_ERROR_CODE(n) void isr##n(interrupt_frame_t* frame) { isr_common(frame, 0); }
//#define ISR_DEFINITION_ERROR_CODE(n) void isr##n(interrupt_frame_t* frame, uint32_t error_code) { isr_common(frame, error_code); }
//
//
//ISR_DEFINITION_NO_ERROR_CODE(0);
//ISR_DEFINITION_NO_ERROR_CODE(1);
//ISR_DEFINITION_NO_ERROR_CODE(2);
//ISR_DEFINITION_NO_ERROR_CODE(3);
//ISR_DEFINITION_NO_ERROR_CODE(4);
//ISR_DEFINITION_NO_ERROR_CODE(5);
//ISR_DEFINITION_NO_ERROR_CODE(6);
//ISR_DEFINITION_NO_ERROR_CODE(7);
//ISR_DEFINITION_ERROR_CODE(8);
//ISR_DEFINITION_NO_ERROR_CODE(9);
//ISR_DEFINITION_ERROR_CODE(10);
//ISR_DEFINITION_ERROR_CODE(11);
//ISR_DEFINITION_ERROR_CODE(12);
//ISR_DEFINITION_ERROR_CODE(13);
//ISR_DEFINITION_ERROR_CODE(14);
//ISR_DEFINITION_NO_ERROR_CODE(15);
//ISR_DEFINITION_NO_ERROR_CODE(16);
//ISR_DEFINITION_NO_ERROR_CODE(17);
//ISR_DEFINITION_NO_ERROR_CODE(18);
//ISR_DEFINITION_NO_ERROR_CODE(19);
//ISR_DEFINITION_NO_ERROR_CODE(20);
//ISR_DEFINITION_NO_ERROR_CODE(21);
//ISR_DEFINITION_NO_ERROR_CODE(22);
//ISR_DEFINITION_NO_ERROR_CODE(23);
//ISR_DEFINITION_NO_ERROR_CODE(24);
//ISR_DEFINITION_NO_ERROR_CODE(25);
//ISR_DEFINITION_NO_ERROR_CODE(26);
//ISR_DEFINITION_NO_ERROR_CODE(27);
//ISR_DEFINITION_NO_ERROR_CODE(28);
//ISR_DEFINITION_NO_ERROR_CODE(29);
//ISR_DEFINITION_NO_ERROR_CODE(30);
//ISR_DEFINITION_NO_ERROR_CODE(31);
//
////system calls
//ISR_DEFINITION_NO_ERROR_CODE(128);
//ISR_DEFINITION_NO_ERROR_CODE(177);
//
//
//void isr_common(interrupt_frame_t* frame, uint32_t error_code)
//{
//
//}